# Generated by Django 3.2.17 on 2023-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230512_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Flight departure datetime'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Flight duration'),
        ),
    ]
