# Generated by Django 3.2.17 on 2023-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20230512_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(verbose_name='Flight departure datetime'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DateTimeField(verbose_name='Flight duration'),
        ),
    ]
